### ISSUE TITLE
Uploading not working on TeamCity?

### ISSUE THREAD

**Issue by sihil** [guardian/riffraff-artifact#18]
TeamCity gets a copy of the repo content, not an actual git repo. This means this fails: https://github.com/guardian/sbt-riffraff-artifact/blob/master/src/main/scala/com/gu/riffraff/artifact/RiffRaffArtifact.scala#L53-L56

:disappointed:

**Comment by cb372** [comment]
I was just about to report this. We are getting it on the new Platforms :cloud: TeamCity as well.

**Comment by philwills** [comment]
There are two workarounds for this:
- specify those values explicitly
- set the `VCS checkout mode` in the build setting in Teamcity to be `Automatically on agent` 

I haven't verified the latter works, but I'd be pretty confident.
