### ISSUE TITLE
Branch is not set correctly on team city

### ISSUE THREAD

**Issue by mchv** [guardian/riffraff-artifact#32]
Even with `riffRaffManifestVcsUrl` setting, the `branch` field is not populated correctly on `Team City`.
- [build.sbt](https://github.com/guardian/content-api-transformer-lambda/blob/a2982bb92b1d1b7ff969d36f2e7444aa8b80418b/build.sbt) file

```
riffRaffPackageName := "content-api-transformer-lambda"
riffRaffPackageType := (packageBin in Universal).value
riffRaffBuildIdentifier := env("BUILD_NUMBER").getOrElse("DEV")
riffRaffUploadArtifactBucket := Option("riffraff-artifact")
riffRaffUploadManifestBucket := Option("riffraff-builds")
riffRaffManifestVcsUrl := "git@github.com:guardian/content-api-transformer-lambda.git"
```
- [build.json](http://s3://riffraff-builds/content-api-transformer-lambda/53/build.json) produced

``` json
{
  "projectName":"content-api-transformer-lambda",
   "buildNumber":"53",
    "startTime":"2016-10-07T15:28:20.782Z",
    "revision":"Unknown",
    "vcsURL":"git@github.com:guardian/content-api-transformer-lambda.git",
    "branch":""
}
```

**Comment by philwills** [comment]
Unfortunately I haven't found any way round this without adding 

![image](https://cloud.githubusercontent.com/assets/68329/19305081/48a4acae-9067-11e6-97d5-d531adc6bf62.png)

to the Teamcity parameters, which is a bit rubbish. 

Alternatively we could work around this with proper support for agent-based checkout, but even then, we I don't know how to make that the default.

**Comment by philwills** [comment]
Oh and you'll need 

``` scala
riffRaffManifestBranch := env("BRANCH_NAME").getOrElse("unknown_branch")
```

at which point the plugin isn't providing that much value.

**Comment by sihil** [comment]
You can totally do this with the default TC setup although it's a bit of a faff.
1. Read the properties file named in the environment variable `build.properties.file`
2. Within that properties file, read the properties file named in the key `teamcity.configuration.properties.file`
3. 🎉  You have a properties object containing the VCS url and branch information

(I started writing stuff to do this ages ago but it never got finished: https://github.com/guardian/sbt-version-info-plugin/blob/sh-json-version-info/src/main/scala/com/gu/versioninfo/VersionInfo.scala)

**Comment by philwills** [comment]
Ooh, thanks @sihil. That feels like it's probably worth a go, even if it's a faff.

**Comment by sihil** [comment]
Yep - totally agree. Just haven't got around to it yet. Think it's worth a push to make this plugin work with minimal config in TC/Circle/Travis.

**Comment by mchv** [comment]
@philwills thanks! I will use the workaround for the time being and will try to contribute the @sihil logic if I find some time this week

**Comment by alexduf** [comment]
fixed here :)
https://github.com/guardian/sbt-riffraff-artifact/pull/34
