### ISSUE TITLE
Riffraff doesn't fail when artifact does not get uploaded in s3

### ISSUE THREAD

**Issue by thomaska** [guardian/riffraff-artifact#35]
Perquisites:
-Project that uses Riffraff (Build 612)
-Uses `riffraffUpload` in its build
-Does not have `env.AWS_ACCESS_KEY_ID` or `env.AWS_SECRET_KEY` parameters set.

Steps to reproduce:
-Run a build of the project, that publishes artifacts in RiffRaff (eg. using Teamcity).

Expected:
-Publishing artifacts should fail

Reality:
-Τhe following messages appear in the Build log.
```
[11:58:11]Publishing internal artifacts
[11:58:11][Publishing internal artifacts] Publishing 1 file using [ArtifactsCachePublisher]
[11:58:12][Publishing internal artifacts] Publishing 1 file using [WebPublisher]
[11:58:12]About to upload artifacts to S3
[11:58:12]Artifact S3 upload complete
```

Details:
- The project that this issue was noticed is `discussion-api`.
- The reason it was realised that the artifact hasn't been uploaded was that the relevant build could not be found in RiffRaff.

PS. as a workaround `riffRaffNotifyTeamcity` can be used instead.

**Comment by philwills** [comment]
If you're building on a machine with instance profile credentials, it will successfully upload, even without those parameters. I believe that's what's happening in this scenario.

Feel free to reopen if that's not the case.

**Comment by thomaska** [comment]
I see, ok. 
Although I was thinking that the issue is that the "Artifact S3 upload complete" is a bit misleading, not the reason why it doesn't get uploaded?

**Comment by philwills** [comment]
I believe it did get uploaded and that wasn't a lie, but I could be mistaken.

**Comment by thomaska** [comment]
In Riffraff, we couldn't see the relevant build to deploy it (were getting s3 exception), that's why it was assumed that probably it wasn't uploaded. But maybe I'm missing something.
And actually @sihil suggested to open an issue, but maybe I didn't understand correctly!

**Comment by philwills** [comment]
No, you may well be right, I'll dig a bit more.
